import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:csv/csv.dart';
import 'package:equatable/equatable.dart';

part 'lesson1.dart';
part 'lesson2.dart';
part 'lesson3.dart';
part 'lesson4.dart';
part 'lesson5.dart';
part 'lesson6.dart';
part 'lesson7.dart';
part 'lesson8.dart';
part 'lesson9.dart';
part 'lesson10.dart';
part 'lesson11.dart';
part 'lesson12.dart';
part 'lesson13.dart';
part 'lesson14.dart';
part 'lesson15.dart';
part 'lesson16.dart';
part 'lesson17.dart';
part 'lesson18.dart';
part 'lesson19.dart';
part 'lesson20.dart';
part 'lesson21.dart';
part 'lesson22.dart';
part 'lesson23.dart';
part 'lesson24.dart';
part 'lesson25.dart';
part 'lesson26.dart';
part 'lesson27.dart';
// part 'lesson28.dart';
// part 'lesson29.dart';
// part 'lesson30.dart';
